// export const CORE_ACTION_BEGIN = 'CORE_ACTION_BEGIN';
// export const CORE_ACTION_SUCCESS = 'CORE_ACTION_SUCCESS';
// export const CORE_ACTION_FAILURE = 'CORE_ACTION_FAILURE';

export const CORE_GET_UNIVERSE_BEGIN = 'CORE_GET_UNIVERSE_BEGIN'
export const CORE_GET_UNIVERSE_SUCCESS = 'CORE_GET_UNIVERSE_SUCCESS'
export const CORE_GET_UNIVERSE_FAILURE = 'CORE_GET_UNIVERSE_FAILURE'
