// export const CORE_ACTION_BEGIN = 'CORE_ACTION_BEGIN';
// export const CORE_ACTION_SUCCESS = 'CORE_ACTION_SUCCESS';
// export const CORE_ACTION_FAILURE = 'CORE_ACTION_FAILURE';

export const BASKET_ADD_PRESTATION = 'BASKET_ADD_PRESTATION'
export const BASKET_REMOVE_PRESTATION = 'BASKET_REMOVE_PRESTATION'
